### ISSUE TITLE
rendering of tracks and paths

### ISSUE THREAD

**Issue by dp7x** [FreemapSlovakia/freemap-mapnik#241]
Hello
another suggestion for the rendering of tracks (highway=track) and paths (highway=path).
They look very similar in freemap, but usually a track is larger and more confortable than a path: in a track maybe you can go with a car or farm tractor, while in the path you can just walk and maybe go with a bike.

Here is a sample from the satellite view:
![image](https://user-images.githubusercontent.com/103643938/165547226-fb4a6904-96fb-4aef-8d32-b21c2c76b746.png)

In OSM standard layer the track is rendered easily distinguishable from a path:
![image](https://user-images.githubusercontent.com/103643938/165547589-e20b0f7d-3bb5-402c-8ace-f106be7dbfd6.png)

In freemap they are different, yes, but not easy distinguishable :
![image](https://user-images.githubusercontent.com/103643938/165547949-9f7e9471-a2ce-43e2-82a5-cd24962fd1d2.png)

Could you consider rendering tracks a little wider than now, or maybe use a different color ?
Thank you

**Comment by zdila** [comment]
It duplicates #89 and #93 (sorry they are reported in Slovak language). I personally find current rendering good, because also in the terrain there are many tracks hardly distinguishable from paths and vice versa. I personally have also no problem to distinguish track and path in the map as path is slightly thinner with much denser dashing. In any case you can create PR ideally with screenshot to see your proposal or at least near-to-real looking mockup in some drawing program.

**Comment by dp7x** [comment]
Hello Martin
The way path and tracks are rendered is good, I would just make track line a little wider than path, without changing the actual style and color. So, if path line is 5 pixels wide, I would make the track line 8 or 10 pixels.
Here is a (horrible) sample I tried to prepare with Paint:
![track_path](https://user-images.githubusercontent.com/103643938/165756242-6faf5ec2-712e-49e4-9d8c-bcec55c519b6.png)
