### ISSUE TITLE
Show guideposts only on lower zoom levels

### ISSUE THREAD

**Issue by Apflkuacha** [FreemapSlovakia/freemap-mapnik#265]
Currently the guideposts are shown already on zoom 12. These guideposts are really small details and should be drawn starting from zoom 16. Here a screenshot of how it looks like in some areas: 
![image](https://user-images.githubusercontent.com/31316050/195456618-cc3ce9a6-d79b-4432-b4eb-73079695c74f.png)

By the way: awesome map you are styling - especially the shading and the detailed contour lines are perfect! But it has to be improved in some details

**Comment by zdila** [comment]
I must admit that the map is primarily being styled for Slovakia where this problem is absent.

Also [the area](https://www.freemap.sk/#map=15/47.253995/9.643914&layers=XI) you posted contains lot of strange guideposts (strange names). Maybe they should be retagged to [route markers](https://wiki.openstreetmap.org/wiki/Tag:information=route_marker) which are rendered from higher zooms? This place is very specific and doesn't seem to be a common problem in Austria.

I can try to render guideposts from Z13 and will decide, but in no case from Z16. It would be way too much. Guideposts (not only) in Slovakia are used by their name for identifying the places, routes and for the navigation in the terrain and this information would be missed.

**Comment by zdila** [comment]
guideposts are now rendered from z13
